# Generated by Django 5.2.8 on 2025-11-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_category_deal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
